language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

notifications:
  email: false
  slack:
    secure: AqHB172t10a7gJhGPSm94/eTgHmA7TcKGUBajMiIIkgp4Lmf5GP52JBp8Cip4kzkPeijawavK0pOFIs+2ps+11OAtsRNZ8TSSYIgfCD9n4GyAslFSw3QOCbVW4OcghH2GgH87dG773812DfJbUdK/HEMlu4kRVBPsoGzKK3IaTAPi9CiEq8Z8Qg9+BZkzf1a0HE/ym+ViuXKJpqQHaV5i5HFOCKV4kylEcZj4vxc9XZbx2wO/py1p9ez2YVH0cF1mxGNRqAQIjFHWtthJqldDU9Ufp9L9EKGDm7h/LK9MPGCPeFKoxvBa3wf6SDavAXgcGGZi1s24XFZklZNgSN4VaMKKa4T1PVdecQIayyoYGZX4JfXl0Bgg7I5sbVI3DeX8nSGwoGsXdli1i53aQ9feWVXGpQIJuM86NrmPFRB8qMRZcJDN8VuAyAaIKH/e5gCikG8qNgA+dphfPAY8Es3M/cJQOV29JkmFq3wddikxfQEKkJPv2Y9Q9pe8B9y5rPyFfuS7tErh/iLb68tpWSWXvgVxwqv5gx+6f0bm6J4pAvle0AuPRXBDdXwkCqdz6Ut5rI/GzzwqA3KIyDEaU1s93syfue54f29oPn27aWqoqATW41RjQCH9MkDD+4+KPFVAFYZY4oP80uFC3gBjoAvUYYTO/fypv8p/CwZ/XjNZg0=

env:
  - ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0
  - ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0
  - ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0 COVERAGE=true
  - ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=~7.0 COVERAGE=true

matrix:
  exclude:
    - php: 7.0
      env: ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0
    - php: 7.0
      env: ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0 COVERAGE=true
    - php: 7.1
      env: ILLUMINATE_VERSION=5.1.* PHPUNIT_VERSION=~4.0
    - php: 7.1
      env: ILLUMINATE_VERSION=5.2.* PHPUNIT_VERSION=~4.0
    - php: 7.1
      env: ILLUMINATE_VERSION=5.3.* PHPUNIT_VERSION=~5.0

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update --prefer-dist --no-interaction --no-suggest
  - composer require "orchestra/testbench:${ILLUMINATE_VERSION/5\./3\.}" --no-update --prefer-dist --no-interaction --no-suggest
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
